-- Script de inicialización para la base de datos Oracle
-- TodoList con Clean Architecture

-- Crear secuencia para IDs
CREATE SEQUENCE TODO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Crear tabla de todos
CREATE TABLE TODOS (
    ID NUMBER(19) PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    COMPLETED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Insertar algunos datos de ejemplo (opcional)
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, COMPLETED, CREATED_AT, UPDATED_AT)
VALUES (TODO_SEQ.NEXTVAL, 'Aprender Clean Architecture', 'Estudiar los principios de Clean Architecture', 0, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODOS (ID, TITLE, DESCRIPTION, COMPLETED, CREATED_AT, UPDATED_AT)
VALUES (TODO_SEQ.NEXTVAL, 'Configurar base de datos Oracle', 'Configurar conexión a Oracle Database', 1, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODOS (ID, TITLE, DESCRIPTION, COMPLETED, CREATED_AT, UPDATED_AT)
VALUES (TODO_SEQ.NEXTVAL, 'Crear API REST', 'Implementar endpoints para CRUD de Todos', 0, SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;